baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Matthew Kao"
    subtitle: "Graduated from UC Berkeley with a Bachelor's Degree in Computer Science at 19"
    content: "A young software engineer specializing in web and mobile app development. I am currently looking for new opportunities post-graduation and am open to any opportunities in the field of computer science."
    image: /images/gradpic.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1WHTjjbHk4_90pq1GXyrWv3YQXhoOiPHN/view?usp=sharing"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/mattkao
        - icon: fab fa-github
          url: https://github.com/Matthew-Kao

  # skills
  skills:
    - category: "Frontend"
      skills:
        - name: "React"
          logo: "logos/React.png"
        - name: "HTML"
          logo: "logos/Html.png"
        - name: "CSS"
          logo: "logos/Css.png"
        - name: "JavaScript"
          logo: "logos/Javascript.png"
        - name: "Bootstrap"
          logo: "logos/bootstrap.png"
        - name: "Flutter"
          logo: "logos/Flutter.png"
    - category: "Backend"
      skills:
        - name: "Node.js"
          logo: "logos/nodejs.png"
        - name: "MySQL"
          logo: "logos/mysql.png"
        - name: "PostgreSQL"
          logo: "logos/postgresql.png"
        - name: "MongoDB"
          logo: "logos/mongodb.png"
        - name: "Firebase"
          logo: "logos/Firebase.png"
    - category: "Languages"
      skills:
        - name: "Python"
          logo: "logos/python.png"
        - name: "C++"
          logo: "logos/c++.png"
        - name: "Java"
          logo: "logos/java.png"
        - name: "C"
          logo: "logos/c.png"
        - name: "Dart"
          logo: "logos/dart.png"
        - name: "Ruby"
          logo: "logos/ruby.png"
    - category: "Tools"
      skills:
        - name: "GitHub"
          logo: "logos/github.png"
        - name: "AWS"
          logo: "logos/aws.png"
        - name: "GCP"
          logo: "logos/gcp.png"
        - name: "Figma"
          logo: "logos/figma.png"

  # About
  # about:
  #   enable: true
  #   title: "About Me"
  #   image: "/images/me.png"
  #   content: |-
  #     I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA.

  #     I am currently working on a project that will be used to help people find the best way to get around the city.
  #   skills:
  #     enable: true
  #     title: "Here are a few technologies I've been working with recently:"
  #     items:
  #       - "HTML"
  #       - "CSS"
  #       - "JavaScript"
  #       - "React"
  #       - "Node"
  #       - "Express"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Arts in Computer Science"
        school:
          name: "University of California, Berkeley"
          url: "https://www.berkeley.edu/"
          logo: "logos/ucb.png"
        date: "2021 - 2023"
        GPA: "3.7 out of 4.0"
      - title: "Associate of Science in Computer Science"
        school:
          name: "Diablo Valley College"
          url: "https://www.dvc.edu/"
          logo: "logos/dvc.png"
        date: "2019 - 2021"
        GPA: "4.0 out of 4.0"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Web Developer"
        company: "Certified Employment Group"
        companyUrl: "https://www.certifiedemployment.com/job-openings.php"
        date: "Oct 2023 - Mar 2024"
        content: "At Certified Employment Group, I spearheaded the revitalization of web interfaces, employing HTML5, CSS, and JavaScript to significantly improve user experience. My expertise in utilizing Flutter enabled a seamless, responsive design across various devices, enhancing accessibility and consistency. By developing Python-based server-side applications, I introduced advanced algorithms for data caching and asynchronous processing, which notably reduced API response times and optimized database query efficiency. Implementing a comprehensive Selenium testing framework, I achieved a remarkable 96% pass rate on automated tests, substantially minimizing production bugs and bolstering the web application's reliability. My efforts not only refined the technical landscape but also fostered a more engaging and dependable user environment."
      - job: "Lead Mobile Developer"
        company: "Dbrief.AI"
        companyUrl: "https://dbrief.ai"
        date: "May 2022 - Dec 2022"
        content: "At DBRIEF.AI in Berkeley, CA, as the Lead App Developer, I successfully led the development of their mobile application from scratch, utilizing Dart and Flutter. My role encompassed designing the user interface with Figma, adhering to UX design best practices and integrating user feedback to enhance overall usability and satisfaction. I was instrumental in architecting the backend API synchronization, facilitating dynamic content updates aligned with the latest news, which contributed to a significant 15% growth in daily active users. I harnessed Firebase's real-time database capabilities for dynamic data updates, thus enhancing the app's responsiveness and ensuring timely information delivery to users. My innovation included developing a 'Tinder-style' swiping feature, leading to a 20% increase in user engagement time. Furthermore, I guided and mentored a team of four through agile development cycles, ensuring cross-functional collaboration and timely application delivery."
      - job: "Lead Mobile Developer"
        company: "Dbrief.AI"
        companyUrl: "https://dbrief.ai"
        date: "May 2022 - Dec 2022"
        content: "At DBRIEF.AI in Berkeley, CA, as the Lead App Developer, I successfully led the development of their mobile application from scratch, utilizing Dart and Flutter. My role encompassed designing the user interface with Figma, adhering to UX design best practices and integrating user feedback to enhance overall usability and satisfaction. I was instrumental in architecting the backend API synchronization, facilitating dynamic content updates aligned with the latest news, which contributed to a significant 15% growth in daily active users. I harnessed Firebase's real-time database capabilities for dynamic data updates, thus enhancing the app's responsiveness and ensuring timely information delivery to users. My innovation included developing a 'Tinder-style' swiping feature, leading to a 20% increase in user engagement time. Furthermore, I guided and mentored a team of four through agile development cycles, ensuring cross-functional collaboration and timely application delivery."

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:gurusabarisha@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
